#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE logto;
    CREATE USER $POSTGRES_LOGTO_USERNAME WITH ENCRYPTED PASSWORD '$POSTGRES_LOGTO_PASSWORD' CREATEROLE;
    GRANT ALL PRIVILEGES ON DATABASE logto TO $POSTGRES_LOGTO_USERNAME;
    \c logto
    GRANT ALL ON SCHEMA public TO $POSTGRES_LOGTO_USERNAME;
EOSQL
