#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE meshcorehub;
    CREATE USER $POSTGRES_MESHCOREHUB_USERNAME WITH ENCRYPTED PASSWORD '$POSTGRES_MESHCOREHUB_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE meshcorehub TO $POSTGRES_MESHCOREHUB_USERNAME;
EOSQL
