# MeshCore Hub - Staging Environment
# Includes OAuth2 Proxy for authentication

services:
  # === OAUTH2 PROXY (Staging) ===

  oauth2-proxy-stg:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
    container_name: oauth2-proxy-stg
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ../config/oauth2-proxy/templates:/templates:ro
    environment:
      - OAUTH2_PROXY_PROVIDER=github
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
      - OAUTH2_PROXY_COOKIE_SECURE=true
      - OAUTH2_PROXY_COOKIE_NAME=_oauth2_proxy
      - OAUTH2_PROXY_COOKIE_DOMAIN=.${ROOT_DOMAIN}
      - OAUTH2_PROXY_REDIRECT_URL=https://beta.${ROOT_DOMAIN}/oauth2/callback
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_GITHUB_ORG=${OAUTH2_PROXY_GITHUB_ORG:-}
      - OAUTH2_PROXY_GITHUB_USERS=${OAUTH2_PROXY_GITHUB_USERS:-}
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_REVERSE_PROXY=true
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
      - OAUTH2_PROXY_SKIP_AUTH_REGEX=^/($|[^a]|a[^/])
    command:
      - --upstream=http://hub-web-stg:8080
      - --custom-templates-dir=/templates
    labels:
      - "traefik.enable=true"
      # All routes (auth skipped for non-/admin via SKIP_AUTH_REGEX)
      - "traefik.http.routers.oauth2-proxy-stg.rule=Host(`beta.${ROOT_DOMAIN}`) || HostRegexp(`^.+\\.beta\\.${ROOT_DOMAIN}$`)"
      - "traefik.http.routers.oauth2-proxy-stg.priority=50"
      - "traefik.http.routers.oauth2-proxy-stg.entrypoints=websecure"
      - "traefik.http.routers.oauth2-proxy-stg.tls.certresolver=default"
      - "traefik.http.routers.oauth2-proxy-stg.tls.domains[0].main=beta.${ROOT_DOMAIN}"
      - "traefik.http.routers.oauth2-proxy-stg.tls.domains[0].sans=*.beta.${ROOT_DOMAIN}"
      # /oauth2 routes (for auth flow on stg domain)
      - "traefik.http.routers.oauth2-proxy-stg-auth.rule=(Host(`beta.${ROOT_DOMAIN}`) || HostRegexp(`^.+\\.beta\\.${ROOT_DOMAIN}$`)) && PathPrefix(`/oauth2`)"
      - "traefik.http.routers.oauth2-proxy-stg-auth.priority=100"
      - "traefik.http.routers.oauth2-proxy-stg-auth.entrypoints=websecure"
      - "traefik.http.routers.oauth2-proxy-stg-auth.tls.certresolver=default"
      - "traefik.http.services.oauth2-proxy-stg.loadbalancer.server.port=4180"

  # === HUB SERVICES ===

  hub-collector-stg:
    image: ghcr.io/ipnet-mesh/meshcore-hub:main
    container_name: hub-collector-stg
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ../data/hub/stg:/data
      - ${HUB_SEED_HOME}:/seed
    environment:
      - LOG_LEVEL=${HUB_LOG_LEVEL:-INFO}
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - MQTT_USERNAME=${MQTT_USERNAME:-}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-}
      - MQTT_PREFIX=meshcore
      - DATA_HOME=/data
      - SEED_HOME=/seed
      - NODE_CLEANUP_DAYS=${HUB_NODE_CLEANUP_DAYS}
    command: ["collector"]
    healthcheck:
      test: ["CMD", "meshcore-hub", "health", "collector"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  hub-api-stg:
    image: ghcr.io/ipnet-mesh/meshcore-hub:main
    container_name: hub-api-stg
    restart: unless-stopped
    networks:
      - proxy
    depends_on:
      hub-collector-stg:
        condition: service_started
    volumes:
      - ../data/hub/stg:/data
    environment:
      - LOG_LEVEL=${HUB_LOG_LEVEL:-INFO}
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - MQTT_USERNAME=${MQTT_USERNAME:-}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-}
      - MQTT_PREFIX=${MQTT_PREFIX:-meshcore}
      - DATA_HOME=/data
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - API_READ_KEY=${HUB_API_READ_KEY:-}
      - API_ADMIN_KEY=${HUB_API_ADMIN_KEY:-}
    command: ["api"]
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hub-api-stg.rule=Host(`api.beta.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.hub-api-stg.priority=100"
      - "traefik.http.routers.hub-api-stg.entrypoints=websecure"
      - "traefik.http.routers.hub-api-stg.tls.certresolver=default"
      - "traefik.http.services.hub-api-stg.loadbalancer.server.port=8000"

  hub-web-stg:
    image: ghcr.io/ipnet-mesh/meshcore-hub:main
    container_name: hub-web-stg
    restart: unless-stopped
    networks:
      - proxy
    depends_on:
      hub-api-stg:
        condition: service_healthy
    volumes:
      - ../pages:/pages
    environment:
      - LOG_LEVEL=${HUB_LOG_LEVEL:-INFO}
      - API_BASE_URL=http://hub-api-stg:8000
      - API_KEY=${HUB_API_ADMIN_KEY:-}
      - WEB_HOST=0.0.0.0
      - WEB_PORT=8080
      - WEB_ADMIN_ENABLED=true
      - NETWORK_NAME=${HUB_NETWORK_NAME:-MeshCore Network}
      - NETWORK_CITY=${HUB_NETWORK_CITY:-}
      - NETWORK_COUNTRY=${HUB_NETWORK_COUNTRY:-}
      - NETWORK_RADIO_CONFIG=${HUB_NETWORK_RADIO_CONFIG:-}
      - NETWORK_CONTACT_EMAIL=${HUB_NETWORK_CONTACT_EMAIL:-}
      - NETWORK_CONTACT_DISCORD=${HUB_NETWORK_CONTACT_DISCORD:-}
      - NETWORK_CONTACT_GITHUB=${HUB_NETWORK_CONTACT_GITHUB:-}
      - NETWORK_WELCOME_TEXT=${HUB_NETWORK_WELCOME_TEXT:-}
      - PAGES_HOME=/pages
    command: ["web"]
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      # Traffic routed via oauth2-proxy-stg upstream
      - "traefik.enable=false"

  hub-migrate-stg:
    image: ghcr.io/ipnet-mesh/meshcore-hub:main
    container_name: hub-migrate-stg
    restart: on-failure
    volumes:
      - ../data/hub/stg:/data
    environment:
      - LOG_LEVEL=${HUB_LOG_LEVEL:-INFO}
      - DATA_HOME=/data
    command: ["db", "upgrade"]

  # hub-seed-stg:
  #   image: ghcr.io/ipnet-mesh/meshcore-hub:main
  #   container_name: hub-seed-stg
  #   restart: on-failure
  #   volumes:
  #     - ../data/hub/stg:/data
  #     - ${HUB_SEED_HOME}:/seed:ro
  #   environment:
  #     - LOG_LEVEL=${HUB_LOG_LEVEL:-INFO}
  #     - DATA_HOME=/data
  #     - SEED_HOME=/seed
  #   command: ["collector", "seed"]

networks:
  proxy:
    external: true
