name: Daily MQTT Publish

on:
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 9:00 AM UTC
  workflow_dispatch:
    inputs:
      topic_suffix:
        description: 'MQTT topic suffix (e.g., send_msg)'
        required: true
        default: 'send_msg'
        type: string
      message:
        description: 'JSON message payload'
        required: true
        default: '{"timestamp": "2024-01-01T00:00:00Z", "source": "github-actions"}'
        type: string

jobs:
  mqtt-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install mosquitto clients
      run: |
        sudo apt-get update
        sudo apt-get install -y mosquitto-clients
    
    - name: Publish MQTT message
      env:
        MQTT_HOST: ${{ vars.MQTT_HOST }}
        MQTT_PORT: ${{ vars.MQTT_PORT }}
        MQTT_TOPIC_PREFIX: ${{ vars.MQTT_TOPIC_PREFIX }}
        MQTT_USERNAME: ${{ secrets.MQTT_USERNAME }}
        MQTT_PASSWORD: ${{ secrets.MQTT_PASSWORD }}
      run: |
        # Set default values for scheduled runs
        TOPIC_SUFFIX="${{ github.event.inputs.topic_suffix || 'send_msg' }}"
        MESSAGE="${{ github.event.inputs.message || '{\"timestamp\": \"'$(date -Iseconds)'\", \"source\": \"github-actions\", \"type\": \"daily-heartbeat\"}' }}"
        
        # Construct full topic
        FULL_TOPIC="${MQTT_TOPIC_PREFIX}/${TOPIC_SUFFIX}"
        
        echo "Publishing to topic: $FULL_TOPIC"
        echo "Message: $MESSAGE"
        
        # Publish message using mosquitto_pub
        mosquitto_pub \
          -h "$MQTT_HOST" \
          -p "$MQTT_PORT" \
          -u "$MQTT_USERNAME" \
          -P "$MQTT_PASSWORD" \
          -t "$FULL_TOPIC" \
          -m "$MESSAGE" \
          --capath /etc/ssl/certs \
          -q 1
        
        echo "Message published successfully"