name: "MQTT Post: Daily"

on:
  schedule:
    - cron: '0 9 * * *'  # Runs daily at 9:00 AM UTC
  workflow_dispatch:  # Allows manual triggering of the workflow
jobs:
  MQTTPublish:
    runs-on: ubuntu-latest

    steps:
    - name: Install mosquitto clients
      run: |
        sudo apt-get update
        sudo apt-get install -y mosquitto-clients

    - name: Publish MQTT message
      env:
        MQTT_HOST: ${{ vars.MQTT_HOST }}
        MQTT_PORT: ${{ vars.MQTT_PORT }}
        MQTT_TOPIC_PREFIX: ${{ vars.MQTT_TOPIC_PREFIX }}
        MQTT_USERNAME: ${{ secrets.MQTT_USERNAME }}
        MQTT_PASSWORD: ${{ secrets.MQTT_PASSWORD }}
        MESHCORE_CHANNEL_IDX: ${{ vars.MESHCORE_CHANNEL_IDX }}
        MESSAGE_PREFIX: ${{ vars.MESSAGE_PREFIX }}
      run: |
        # Set default values for scheduled runs
        TOPIC_SUFFIX="command/send_chan_msg"
        MESSAGE="{\"channel\": ${MESHCORE_CHANNEL_IDX}, \"message\": \"${MESSAGE_PREFIX}: Daily MQTT Publish Test\"}"

        # Construct full topic
        FULL_TOPIC="${MQTT_TOPIC_PREFIX}/${TOPIC_SUFFIX}"

        echo "Publishing to topic: $FULL_TOPIC"
        echo "Message: $MESSAGE"

        # Publish message using mosquitto_pub
        mosquitto_pub \
          -h "${MQTT_HOST}" \
          -p "${MQTT_PORT}" \
          -u "${MQTT_USERNAME}" \
          -P "${MQTT_PASSWORD}" \
          -t "${FULL_TOPIC}" \
          -m "${MESSAGE}" \
          -q 1

        echo "Message published successfully"
