name: "AI inference"
on: workflow_dispatch

jobs:
  Inference:
    permissions:
      models: read
    runs-on: ubuntu-latest
    steps:

      - name: Weather
        id: weather
        run: |
          json="$(curl https://api.open-meteo.com/v1/forecast?latitude=${{ vars.WEATHER_LATITUDE }}&longitude=${{ vars.WEATHER_LONGITUDE }}&forecast_days=${{ vars.WEATHER_FORECAST_DAYS }}&current=temperature_2m)"
          echo "WEATHER_JSON=$json" >> $GITHUB_ENV

      - name: Test Local Action
        id: inference
        uses: actions/ai-inference@v1
        with:
          prompt: |
            Summarise the following weather report in a single sentence:
            ${{ env.WEATHER_JSON }}

      - name: Print Output
        id: output
        run: echo "${{ steps.inference.outputs.response }}"