name: "AI inference"
on: workflow_dispatch

jobs:
  Inference:
    permissions:
      models: read
    runs-on: ubuntu-latest
    steps:

      - name: Get Weather
        id: weather
        run: |
          json=$(curl "https://api.open-meteo.com/v1/forecast?latitude=${{ vars.WEATHER_LATITUDE }}&longitude=${{ vars.WEATHER_LONGITUDE }}&forecast_days=${{ vars.WEATHER_FORECAST_DAYS }}&hourly=temperature_2m,precipitation_probability,wind_speed_10m")
          echo "WEATHER_JSON=${json}" >> ${GITHUB_ENV}

      - name: Test Local Action
        id: inference
        uses: actions/ai-inference@v1
        with:
          prompt: |
            You are a local weather reporter for Ipswich, UK.
            Provide a concise summary of the day's weather.
            Response MUST NOT exceed 160 characters.
            Use the following JSON data to inform your report:
            ${{ env.WEATHER_JSON }}

      - name: Print Output
        id: output
        run: echo "${{ steps.inference.outputs.response }}"